// Autogenerated from Pigeon (v10.1.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTTakePhotoHostApi.
NSObject<FlutterMessageCodec> *FLTTakePhotoHostApiGetCodec(void);

/// Flutter call Native
@protocol FLTTakePhotoHostApi
- (void)takeCardPhotoIsBack:(NSNumber *)isBack completion:(void (^)(FlutterStandardTypedData *_Nullable, FlutterError *_Nullable))completion;
- (void)takeSelfPhotoIsHand:(NSNumber *)isHand completion:(void (^)(FlutterStandardTypedData *_Nullable, FlutterError *_Nullable))completion;
@end

extern void FLTTakePhotoHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTTakePhotoHostApi> *_Nullable api);

/// The codec used by FLTTakePhotoFlutterApi.
NSObject<FlutterMessageCodec> *FLTTakePhotoFlutterApiGetCodec(void);

/// Native call Flutter
@interface FLTTakePhotoFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onTakeCardPhotoIsBack:(NSNumber *)isBack data:(nullable FlutterStandardTypedData *)data completion:(void (^)(FlutterError *_Nullable))completion;
- (void)onTakeSelfPhotoIsHand:(NSNumber *)isHand data:(nullable FlutterStandardTypedData *)data completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
